services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
  backend:
    image: mcr.microsoft.com/dotnet/aspnet:8.0
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8082:8080
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=mydatabase;User=user;Password=password
    networks:
      - app-network
  frontend:
    image: node:22
    container_name: vue_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 5173:5173
    networks:
      - app-network
    depends_on:
      - backend
    environment:
      - VUE_APP_API_URL=http://backend:5000

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
  node_modules:
